ALTER TABLE car_features ADD COLUMN version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE car_models ADD COLUMN version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE maintenances ADD COLUMN version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE notes ADD COLUMN version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE reservations ADD COLUMN version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE vehicles ADD COLUMN version BIGINT NOT NULL DEFAULT 1;
